// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxeukkvwqdgchzjptbmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZXVra3Z3cWRnY2h6anB0Ym1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1Njc4ODgsImV4cCI6MjA1MzE0Mzg4OH0.gXq_PZqc3DjKy42wtOTBCpjKC1rhuo1AVCoTNAdAAqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);